# -*- coding: utf-8 -*-
"""E-commerce customer behavior.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eph0vcb8yXgFsr6oMitRmxFtClvRPU64
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Data Generation (Task 1)
np.random.seed(42)
n_entries = 500

data = {
    'CustomerID': range(1, n_entries + 1),
    'Age': np.random.randint(18, 71, size=n_entries),
    'PurchaseAmount': np.random.gamma(shape=2.0, scale=50.0, size=n_entries),
    'TransactionFrequency': np.random.poisson(lam=5, size=n_entries),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], size=n_entries)
}

df = pd.DataFrame(data)

# 2. Data Cleaning & Exploration (Task 2)
# Checking for missing values and ensuring data types
df.isnull().sum()
df['Region'] = df['Region'].astype('category')

# 3. Descriptive Statistics (Task 3)
stats = df[['PurchaseAmount', 'Age']].describe()
quartiles = df[['PurchaseAmount', 'Age']].quantile([0.25, 0.5, 0.75])

# 4. Visualizations (Task 4)
plt.figure(figsize=(12, 5))

# Plot 1: Histogram of PurchaseAmount
plt.subplot(1, 2, 1)
sns.histplot(df['PurchaseAmount'], kde=True, color='teal')
plt.title('Distribution of Purchase Amount')

# Plot 2: Bar chart of Avg Transaction Frequency by Region
plt.subplot(1, 2, 2)
sns.barplot(x='Region', y='TransactionFrequency', data=df, palette='magma')
plt.title('Average Transaction Frequency by Region')

plt.tight_layout()
plt.show()

# Display stats for the deliverable
print("Descriptive Statistics:\n", stats)