# -*- coding: utf-8 -*-
"""Exploratory analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eph0vcb8yXgFsr6oMitRmxFtClvRPU64
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# TASK 1: Generate synthetic dataset (minimum 500 rows)
# Features: PurchaseAmount, Age, LoyaltyPoints (Numerical) and Region (Categorical)
np.random.seed(42)
n_rows = 500

data = {
    'CustomerID': range(1, n_rows + 1),
    'Age': np.random.randint(18, 71, size=n_rows),
    'PurchaseAmount': np.random.gamma(shape=2.0, scale=50.0, size=n_rows), # Gamma distribution
    'LoyaltyPoints': np.random.randint(0, 5000, size=n_rows),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], size=n_rows)
}

df = pd.DataFrame(data)

# TASK 2: Data Inspection and Cleaning
print("--- Data Types ---")
print(df.dtypes)
print("\n--- Missing Values ---")
print(df.isnull().sum())

# Calculate summary statistics for all numerical columns
summary_stats = df[['Age', 'PurchaseAmount', 'LoyaltyPoints']].describe()
print("\n--- Descriptive Statistics ---")
print(summary_stats)

# TASK 3: Visualizations
plt.figure(figsize=(15, 5))

# 1. Histogram for PurchaseAmount (Numerical)
plt.subplot(1, 3, 1)
sns.histplot(df['PurchaseAmount'], kde=True, color='teal')
plt.title('Distribution of Purchase Amounts')

# 2. Box Plot: PurchaseAmount across Regions (Numerical vs Categorical)
plt.subplot(1, 3, 2)
sns.boxplot(x='Region', y='PurchaseAmount', data=df, palette='Set2')
plt.title('Purchase Amount by Region')

# 3. Scatter Plot: Age vs LoyaltyPoints (Two Numerical variables)
plt.subplot(1, 3, 3)
sns.scatterplot(x='Age', y='LoyaltyPoints', data=df, alpha=0.6, color='coral')
plt.title('Age vs. Loyalty Points')

plt.tight_layout()
plt.show()